[package]
name = "unbaked-render"
description = "Reference renderer for Unbaked media files"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
unbaked-core = { path = "../unbaked-core" }
