[package]
name = "unbaked-render"
description = "Reference renderer for Unbaked media files"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
harfrust = "0.13.3"
openh264 = "0.9.8"
png = "0.18.1"
rusty_aac = "0.5.0"
serde_json = "1.0.151"
skrifa = "0.46.2"
symphonia = { version = "0.6.1", default-features = false, features = ["aac", "mp3", "flac", "pcm", "wav", "isomp4", "id3v2"] }
unbaked-core = { path = "../unbaked-core" }
unicode-bidi = "0.3.18"
unicode-linebreak = "0.1.5"
unicode-script = "0.5.8"
zune-core = "0.5.3"
zune-jpeg = "0.5.15"
